Hw10
IAGrig/tinkoff-backend-2023 pull request #11
Opened 2023-12-17 20:51 UTC by IAGrig

2023-12-23 22:01 UTC, strelchm commented on src/main/java/edu/hw10/task1/ParametersGenerator.java
> +            if (annotation instanceof Min) {
Можно избежать дублирования кода в методах genetate...

2023-12-23 22:05 UTC, strelchm requested changes
В pull request 10 коммитов, а должен быть один. Необходимо поправить, т к при мердже все зальются. Также покрытие неверно считается

2023-12-30 12:06 UTC, IAGrig commented
Случайно ответвлялся не от master-ветки, исправил это.

2024-01-08 19:20 UTC, strelchm approved these changes

2024-01-23 17:19 UTC, merged