Hw11
IAGrig/tinkoff-backend-2023 pull request #12
Opened 2023-12-17 23:23 UTC by IAGrig

2023-12-24 12:46 UTC, strelchm requested changes
В целом все хорошо, но необходимо исправить, что бы билд проходил, в pull request должен быть один коммит по задаче, что бы верно оценить покрытие тестами

2023-12-24 18:15 UTC, IAGrig commented
Вроде понял свою ошибку, создавал новые ветки не от главной. Не подскажете, как с наименьшим количеством боли это теперь поправить?

2023-12-24 18:18 UTC, strelchm commented
> Вроде понял свою ошибку, создавал новые ветки не от главной. Не подскажете, как с наименьшим количеством боли это теперь поправить?

git-ом из консоли или IIdea пользуетесь?

2023-12-24 19:14 UTC, IAGrig commented
> git-ом из консоли или IIdea пользуетесь?
Из консоли

2023-12-24 20:42 UTC, strelchm commented
> > git-ом из консоли или IIdea пользуетесь?
> > Из консоли

1. Переключиться на главную ветку
2. Создать новую ветку
3. Сделать cherry-pick коммита, который необходимо перенести
4. Сделать пуш созданной ветки (если в имеющуюся ветку, то с флагом --force)

2023-12-26 13:07 UTC, IAGrig commented
Спасибо большое. Извиняюсь за задержки. Я правильно понимаю, что из-за создания новой ветки мне придётся создавать новый pull request? Или можно это как-то обойти и добавить в этот PR?

2023-12-27 14:18 UTC, strelchm commented
> Спасибо большое. Извиняюсь за задержки. Я правильно понимаю, что из-за создания новой ветки мне придётся создавать новый pull request? Или можно это как-то обойти и добавить в этот PR?

PR тот же, локально создается новая ветка, но она пушится в ту же удаленную ветку (которая привязана к PR). Если не получится, можно в первый PR

2023-12-28 14:11 UTC, IAGrig commented
Вроде разобрался. Так ведь должно было получиться?

2023-12-29 08:49 UTC, strelchm commented
> Вроде разобрался. Так ведь должно было получиться?

Молодец, то, что надо. Попробуй еще поправить, что бы build прошел
![image](https://github.com/IAGrig/tinkoff-backend-2023/assets/23243577/33e93ede-5ee3-47a5-9f86-b126ded7f2a5)

2023-12-30 12:08 UTC, IAGrig commented
Поправил общую ошибку для всех веток, осталось конкретно в этой разобраться с ошибкой в зависимостях, которая ломает build

2023-12-30 21:20 UTC, IAGrig commented
Теперь build наконец-то проходит

2024-01-06 17:42 UTC, strelchm approved these changes

2024-01-06 17:42 UTC, strelchm commented on src/test/java/edu/hw11/task2/ArithmeticUtils.java
> +package edu.hw11.task2;
Если класс используется только в тестах, то лучше его перенести в тестовые пакеты, тогда и покрытие будет актуальное

2024-01-23 17:19 UTC, merged