Project3
IAGrig/tinkoff-backend-2023 pull request #6
Opened 2023-11-19 20:52 UTC by IAGrig

2023-12-30 12:03 UTC, IAGrig commented
Случайно ответвлялся не от master-ветки, исправил это.

2024-01-06 21:16 UTC, strelchm requested changes
Плюсом к комментариям: нету тестов, покрытие 0

2024-01-06 21:16 UTC, strelchm commented on src/main/java/edu/project3/LogReport.java
> +    private final HashMap<String, Integer> requestedResources;
nit: Типы переменных желательно делать инетфейса, а не реализации

2024-01-06 21:16 UTC, strelchm commented on src/main/java/edu/project3/CmdArgumentsHandler.java
> +public class CmdArgumentsHandler {
nit: Все методы класса статические, возможно данный класс лучше назвать CmdArgumentsHelper и сделать приватный конструктор? Так как больше похож на класс с вспомогательными функциями

2024-01-06 21:16 UTC, strelchm commented on src/main/java/edu/project3/FilesReader.java
> +        } catch (IOException e) {
nit: Можно объединить исключения:
```
        } catch (IOException | URISyntaxException e) {
            throw new RuntimeException(e);
        }

2024-01-06 21:16 UTC, strelchm commented on src/main/java/edu/project3/LogReport.java
> +    public HashMap<String, Integer> getRequestedResources() {
возвращающий тип желательно, также, не делать типом класса реализации

2024-01-06 21:16 UTC, strelchm commented on src/main/java/edu/project3/Renderer.java
> +public class Renderer {
По условию задания необходимо писать результат не в out-поток, а в файл

2024-01-06 21:16 UTC, strelchm commented on src/main/java/edu/project3/Renderer.java
> +public class Renderer {
В данный класс закинуты обе реализации рендеринга, по хорошему необходимо их разделить по классам и сделать общий интерфейс, что бы было single responsibility

2024-01-08 18:14 UTC, strelchm approved these changes

2024-01-23 17:19 UTC, merged