Hw7
IAGrig/tinkoff-backend-2023 pull request #7
Opened 2023-11-26 20:59 UTC by IAGrig

2023-11-26 22:54 UTC, IAGrig commented
# Метод Монте-Карло при 8 потоках:
- 10млн: 146мс против 451мс (3x ускорение), средняя погрешность 5.6E-4
- 100млн: 403мс против 4390мс (10.9x ускорение), средняя погрешность 1.3E-4
- 1млрд: 3149мс против 43770мс (13.9x ускорение), средняя погрешность 3E-5

2023-12-30 12:04 UTC, IAGrig commented
Случайно ответвлялся не от master-ветки, исправил это.

2024-01-02 15:18 UTC, strelchm requested changes

2024-01-02 15:18 UTC, strelchm commented on src/main/java/edu/hw7/task2/ParallelFactorial.java
> +        return LongStream.range(1, n + 1).parallel().reduce((a, b) -> a * b).getAsLong();
При вычислении факториала для 0 функция падает с ошибкой 
`java.util.NoSuchElementException: No value present

	at java.base/java.util.OptionalLong.getAsLong(OptionalLong.java:130)
	at edu.hw7.task2.ParallelFactorial.calculateFactorial(ParallelFactorial.java:7)
	at edu.hw7.Task2Test.task2Test(Task2Test.java:12)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)`
Воспроизведение в тестах:
`assertThat(ParallelFactorial.calculateFactorial(0)).isEqualTo(1);`

2024-01-02 15:18 UTC, strelchm commented on src/main/java/edu/hw7/task3/Cache.java
> +    public synchronized void add(Person person) {
При явных блокировках через ReentrantReadWriteLock необходим ли syncronized?

2024-01-07 12:26 UTC, strelchm commented
> Случайно ответвлялся не от master-ветки, исправил это.

Когда поправишь, переведи, пожалуйста в личном кабинете, задачи на проверку

2024-01-10 20:15 UTC, strelchm approved these changes

2024-01-23 17:19 UTC, merged