Hw8
IAGrig/tinkoff-backend-2023 pull request #8
Opened 2023-12-04 01:04 UTC by IAGrig

2023-12-18 22:39 UTC, strelchm requested changes

2023-12-18 22:39 UTC, strelchm commented on src/main/java/edu/hw8/task1/Server.java
> +//            Future<String> future = executorService.submit(callable("123"));
верное направление, в отдельном потоке считываем запрос и вовращаем ответ в соответствии с полученным значением из мапы

2023-12-18 22:39 UTC, strelchm commented on src/main/java/edu/hw5/Task1.java
> +package edu.hw5;
лишние коммиты в mr, должно быть одно только задание номер 8

2023-12-18 22:39 UTC, strelchm commented on src/main/java/edu/hw5/Task1.java
> +import java.util.Date;
checkstyle необходимо доработать

2023-12-30 12:04 UTC, IAGrig commented
Случайно ответвлялся не от master-ветки, исправил это.

2024-01-09 19:54 UTC, IAGrig commented
Сравнение производительности перебора паролей в зависимости от количества потоков:
| Длины паролей | 1 поток, секунды | 2 потока, секунды | 4 потока, секунды | 6 потоков, секунды |
| ------------- | ---------------- | ----------------- | ----------------- | ------------------ |
| 1-3           | 0.17             | 0.26 (x 0.65)     | 0.28 (x 0.61)     | 0.27 (x 0.63)      |
| 1-4           | 2.3              | 1.65 (x 1.39)     | 1.15 (x 2.0)      | 1.05 (x 2.19)      |
| 1-5           | 71               | 45.9 (x. 1.55)    | 14.95 (x 4.75)    | 10.1 (x 7.03)      |

2024-01-10 21:04 UTC, strelchm approved these changes

2024-01-23 17:19 UTC, merged